name: '🕷️ Bug report'
description: 'report bugs'
title: '[Bug]'
labels:
  - 'bug'
body:
  - type: markdown
    attributes:
      value: |
        Please **DO NOT** file issues here if you are having problems with ChatGPT itself. Issues should **ONLY** be created here for bugs that pertain to this package, [lencx/ChatGPT](https://github.com/lencx/ChatGPT). If you are experiencing an issue on [chat.openai.com](chat.openai.com), please contact **OpenAI** for support or submit feedback through ChatGPT itself. If you **only have an issue with this app** and do not have the issue on [chat.openai.com](https://chat.openai.com), please file an issue here.
      
        Please make sure to [search for existing issues](https://github.com/lencx/ChatGPT/issues) before filing a new one!
  - type: checkboxes
    attributes:
      label: Non-ChatGPT bug
      options:
        - label: |
            This issue does not occur on chat.openai.com and only occurs on this app.
          required: true
  - type: markdown
    attributes:
      value: |
        ## Bug report
        Please fill in the following information to help us reproduce the bug:
  - type: input
    id: version
    attributes:
      label: Version
      description: 'Please specify the version of ChatGPT you are using, a newer version may have fixed the bug you encountered.Check the [UPDATE_LOG](https://github.com/lencx/ChatGPT/blob/main/UPDATE_LOG.md) for more information.'
      placeholder: 'e.g. v0.1.0'
    validations:
      required: true
  - type: textarea
    id: bug
    attributes:
      label: Bug description
      description: |
        Please describe the bug here,if possible, please provide a minimal example to reproduce the bug.The content of `~/.chatgpt/chatgpt.log` may be helpful if you encounter a crash.
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: OS
      description: 'Please specify the OS you are using.'
      placeholder: 'e.g. Ubuntu 22.04'
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: 'If you think your environment may be related to the problem, please describe it here.'
