FROM --platform=linux/arm64 debian:bullseye

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y \
      build-essential curl git pkg-config \
      libssl-dev libgtk-3-dev libgdk-pixbuf2.0-dev \
      librsvg2-dev libglib2.0-dev cmake python3 \
      nodejs npm \
      aarch64-linux-gnu-gcc aarch64-linux-gnu-g++ \
      qemu-user-static
